// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.30;
import {ZkDPPClaimLedger as L} from "../src/final/ZkDPPClaimLedger.sol";
import {Poseidon2BLS12381} from "../src/generated/Poseidon2BLS12381.sol";
import {M9AuditEntryVerifier} from "../src/M9AuditEntryVerifier.sol";
import {M9AuditTransferVerifier} from "../src/M9AuditTransferVerifier.sol";
import {M9AuditProceedVerifier} from "../src/M9AuditProceedVerifier.sol";
import {M9AuditRecallVerifier} from "../src/M9AuditRecallVerifier.sol";
import {M9AuditMergeVerifier} from "../src/M9AuditMergeVerifier.sol";
import {M9AuditSplitVerifier} from "../src/M9AuditSplitVerifier.sol";
import {M9ExitDPPVerifier} from "../src/M9ExitDPPVerifier.sol";
import {M9AuditProcessVerifier} from "../src/M9AuditProcessVerifier.sol";
import {M9IssueStandardVerifier} from "../src/M9IssueStandardVerifier.sol";
import {M9IssueStrictVerifier} from "../src/M9IssueStrictVerifier.sol";

interface VmM9{function readFile(string calldata)external view returns(string memory);function parseJsonBytes(string calldata,string calldata)external pure returns(bytes memory);function parseJsonUintArray(string calldata,string calldata)external pure returns(uint256[] memory);function parseJsonUint(string calldata,string calldata)external pure returns(uint256);function prank(address)external;function expectRevert(bytes4)external;function warp(uint256)external;function toString(uint256)external pure returns(string memory);}

contract M9FinalIntegrationTest{
 VmM9 constant vm=VmM9(address(uint160(uint256(keccak256("hevm cheat code")))));address constant ISSUER1=address(0x1001);address constant ISSUER3=address(0x1003);address constant STATUS=address(0x4004);
 L ledger;string fixture;address[7] fixedV;M9AuditProcessVerifier processV;M9IssueStandardVerifier standardV;M9IssueStrictVerifier strictV;
 function setUp()public{fixture=vm.readFile("test/fixtures/m9-proofs.json");Poseidon2BLS12381 h=new Poseidon2BLS12381();processV=new M9AuditProcessVerifier();standardV=new M9IssueStandardVerifier();strictV=new M9IssueStrictVerifier();fixedV=[address(new M9AuditEntryVerifier()),address(new M9AuditTransferVerifier()),address(new M9AuditProceedVerifier()),address(new M9AuditRecallVerifier()),address(new M9AuditMergeVerifier()),address(new M9AuditSplitVerifier()),address(new M9ExitDPPVerifier())];ledger=new L(fixedV,address(h),STATUS);ledger.setEntryIssuer(ISSUER1,true);ledger.setEntryIssuer(ISSUER3,true);require(address(ledger).code.length<=24576,"EIP-170");_policies();}
 function _path(uint i)internal view returns(string memory){return string.concat(".Events[",vm.toString(i),"]");}
 function _get(uint i)internal view returns(uint8 k,uint epoch,bytes memory proof,uint256[] memory p,L.AuditCipher memory a){string memory q=_path(i);k=uint8(vm.parseJsonUint(fixture,string.concat(q,".EventKind")));epoch=vm.parseJsonUint(fixture,string.concat(q,".Epoch"));proof=vm.parseJsonBytes(fixture,string.concat(q,".Proof"));uint256[] memory all=vm.parseJsonUintArray(fixture,string.concat(q,".PublicInputs"));uint b=k==0?1:k==1?6:k==2?3:k==3?4:k==4||k==5?4:8;uint parents=k==0?0:k==4?2:k==6?3:1;uint outputs=k==1||k==5||k==6?2:1;p=new uint256[](b);for(uint j;j<b;j++)p[j]=all[j];a.r1X=all[b];a.r1Y=all[b+1];a.encryptedParents=new uint256[](parents);a.encryptedOutputNfs=new uint256[](outputs);for(uint j;j<parents;j++)a.encryptedParents[j]=all[b+2+j];for(uint j;j<outputs;j++)a.encryptedOutputNfs[j]=all[b+2+parents+j];}
 function _execute(uint i)internal returns(uint){(uint8 k,uint epoch,bytes memory proof,uint256[] memory p,L.AuditCipher memory a)=_get(i);if(epoch!=0)vm.warp(epoch*600);if(k==0){vm.prank(i<2?ISSUER1:ISSUER3);return ledger.entry(proof,p[0],a);}if(k==1)return ledger.transfer(proof,p[0],p[1],p[2],p[3],p[4],p[5],a);if(k==2)return ledger.proceed(proof,p[0],p[1],p[2],a);if(k==3)return ledger.recall(proof,p[0],p[1],p[2],p[3],a);if(k==4)return ledger.merge(proof,p[0],p[1],p[2],p[3],a);if(k==5)return ledger.split(proof,p[0],p[1],p[2],p[3],a);uint256[3] memory n=[p[3],p[4],p[5]];uint256[2] memory c=[p[6],p[7]];return ledger.process(proof,p[0],p[1],p[2],n,c,a);}
 function _special(string memory n)internal view returns(bytes memory proof,uint256[] memory p){proof=vm.parseJsonBytes(fixture,string.concat(".",n,".Proof"));p=vm.parseJsonUintArray(fixture,string.concat(".",n,".PublicInputs"));}
 function _policies()internal{ledger.registerPolicyAuthority(address(this));(,,,uint256[] memory pp,)=_get(15);uint pr=ledger.reservePolicy(6);require(pr==pp[0],"process ref");ledger.registerPolicy(pr,3,2,bytes32(uint256(1)),address(processV));ledger.setPolicyGrant(pr,pp[1],true);(,uint256[] memory sp)=_special("Standard");uint sr=ledger.reservePolicy(8);require(sr==sp[0],"standard ref");ledger.registerPolicy(sr,1,1,bytes32(uint256(2)),address(standardV));(,uint256[] memory tp)=_special("Strict");uint tr=ledger.reservePolicyVersion(2);require(tr==tp[0],"strict ref");ledger.registerPolicy(tr,1,1,bytes32(uint256(3)),address(strictV));vm.expectRevert(L.InvalidIssueGrant.selector);ledger.setPolicyGrant(sr,123,true);}
 function _exit(string memory n)internal returns(uint dpp,uint aid){(bytes memory proof,uint256[] memory p)=_special(n);L.AuditCipher memory a;a.r1X=p[3];a.r1Y=p[4];a.encryptedParents=new uint256[](1);a.encryptedParents[0]=p[5];a.encryptedOutputNfs=new uint256[](0);dpp=p[2];aid=ledger.exit(proof,p[0],p[1],p[2],a);}
 function _status(uint8 typ,uint nf,uint8 state)internal{vm.prank(STATUS);ledger.setStatus(typ,nf,state);}function _claimStatus(uint dpp,uint ref,uint8 state)internal{vm.prank(STATUS);ledger.setClaimStatus(dpp,ref,state);}
 function testFinalScenarioPolicyRoutingAndAtomicity()public{for(uint i;i<5;i++)_execute(i);uint firstNF=vm.parseJsonUint(fixture,".FirstVoucherNF");_status(2,firstNF,1);vm.expectRevert(L.InactiveObject.selector);_execute(5);_status(2,firstNF,0);for(uint i=5;i<15;i++)_execute(i);uint processNF=vm.parseJsonUint(fixture,".ProcessInputNF");_status(1,processNF,1);uint beforeID=ledger.nextAuditRecordId();vm.expectRevert(L.InactiveObject.selector);_execute(15);require(ledger.nextAuditRecordId()==beforeID,"process atomic");_status(1,processNF,0);_execute(15);_execute(16);(uint dpp,)=_exit("ProductExit");(bytes memory proof,uint256[] memory p)=_special("Standard");uint sid=ledger.issue(proof,p[0],p[1]);vm.expectRevert(L.DuplicateClaim.selector);ledger.issue(proof,p[0],p[1]);(proof,p)=_special("Strict");uint tid=ledger.issue(proof,p[0],p[1]);(uint wasteDPP,)=_exit("WasteExit");(proof,p)=_special("Standard");vm.expectRevert(L.InvalidProof.selector);ledger.issue(proof,p[0],wasteDPP);_claimStatus(dpp,ledger.getAuditRecord(sid).policyRef,1);_claimStatus(dpp,ledger.getAuditRecord(sid).policyRef,0);_claimStatus(dpp,ledger.getAuditRecord(tid).policyRef,1);_claimStatus(dpp,ledger.getAuditRecord(tid).policyRef,2);require(ledger.noteLeafCount()==19&&ledger.voucherLeafCount()==5&&ledger.nextAuditRecordId()==22,"final counts");(bool ok,uint8 st,)=ledger.verifyClaim(dpp,ledger.getAuditRecord(sid).policyRef);require(ok&&st==0,"standard");(ok,st,)=ledger.verifyClaim(dpp,ledger.getAuditRecord(tid).policyRef);require(ok&&st==2,"strict");require(ledger.producerOf(3,wasteDPP)!=0,"waste DPP");}
}
