package solgen

import (
	"fmt"
	"io"
	"strings"
)

var optimizedVKNames = []string{
	"VK_NB_PUBLIC_INPUTS", "VK_DOMAIN_SIZE", "VK_INV_DOMAIN_SIZE", "VK_OMEGA",
	"VK_QL_COM_X_lo", "VK_QL_COM_X_hi", "VK_QL_COM_Y_lo", "VK_QL_COM_Y_hi",
	"VK_QR_COM_X_lo", "VK_QR_COM_X_hi", "VK_QR_COM_Y_lo", "VK_QR_COM_Y_hi",
	"VK_QM_COM_X_lo", "VK_QM_COM_X_hi", "VK_QM_COM_Y_lo", "VK_QM_COM_Y_hi",
	"VK_QO_COM_X_lo", "VK_QO_COM_X_hi", "VK_QO_COM_Y_lo", "VK_QO_COM_Y_hi",
	"VK_QK_COM_X_lo", "VK_QK_COM_X_hi", "VK_QK_COM_Y_lo", "VK_QK_COM_Y_hi",
	"VK_S1_COM_X_lo", "VK_S1_COM_X_hi", "VK_S1_COM_Y_lo", "VK_S1_COM_Y_hi",
	"VK_S2_COM_X_lo", "VK_S2_COM_X_hi", "VK_S2_COM_Y_lo", "VK_S2_COM_Y_hi",
	"VK_S3_COM_X_lo", "VK_S3_COM_X_hi", "VK_S3_COM_Y_lo", "VK_S3_COM_Y_hi",
	"VK_COSET_SHIFT", "VK_NB_CUSTOM_GATES",
}

func WriteStorageProcessVerifier(w io.Writer, constantSource string) error {
	if len(optimizedVKNames) != OptimizedVKWords {
		return fmt.Errorf("VK name count mismatch")
	}
	lines := strings.Split(constantSource, "\n")
	filtered := make([]string, 0, len(lines))
	removed := 0
	for _, line := range lines {
		trim := strings.TrimSpace(line)
		if strings.HasPrefix(trim, "uint256 private constant VK_") {
			removed++
			continue
		}
		filtered = append(filtered, line)
	}
	if removed != OptimizedVKWords {
		return fmt.Errorf("removed %d VK constants, want %d", removed, OptimizedVKWords)
	}
	s := strings.Join(filtered, "\n")
	s = strings.Replace(s, "contract PlonkVerifier {", "contract StorageProcessVerifier {\n\n  uint256 private constant VK_WORDS = 38;\n  address public immutable vkAdmin = msg.sender;\n  struct StoredVK { bool exists; bytes32 vkHash; uint256[38] words; }\n  mapping(uint256 => StoredVK) private storedVK;\n  event VKRegistered(uint256 indexed policyRef, bytes32 vkHash);\n\n  function registerVK(uint256 policyRef, uint256[38] calldata words, bytes32 vkHash) external {\n    require(msg.sender == vkAdmin, \"not admin\");\n    require(!storedVK[policyRef].exists, \"duplicate VK\");\n    require(vkHash != bytes32(0) && sha256(abi.encode(words)) == vkHash, \"bad VK hash\");\n    StoredVK storage target = storedVK[policyRef];\n    target.exists = true; target.vkHash = vkHash;\n    for (uint256 i = 0; i < VK_WORDS; i++) target.words[i] = words[i];\n    emit VKRegistered(policyRef, vkHash);\n  }\n\n  function getVKWord(uint256 policyRef, uint256 index) external view returns (uint256) {\n    require(index < VK_WORDS, \"bad index\"); return storedVK[policyRef].words[index];\n  }\n\n  function getVKHash(uint256 policyRef) external view returns (bytes32) { return storedVK[policyRef].vkHash; }", 1)
	old := "function Verify(bytes calldata proof, uint256[] calldata public_inputs)\n  public view returns(bool success) {\n\n    assembly {"
	new := "function verifyForPolicy(uint256 policyRef, bytes calldata proof, uint256[] calldata public_inputs)\n  public view returns(bool success) {\n    require(storedVK[policyRef].exists, \"unknown VK\");\n    uint256[38] memory vkWords;\n    for (uint256 i = 0; i < VK_WORDS; i++) vkWords[i] = storedVK[policyRef].words[i];\n\n    assembly {\n      mstore(0x00, vkWords)"
	if !strings.Contains(s, old) {
		return fmt.Errorf("Verify signature not found")
	}
	s = strings.Replace(s, old, new, 1)
	for i, name := range optimizedVKNames {
		replacement := fmt.Sprintf("mload(add(mload(0x00), 0x%x))", i*32)
		s = strings.ReplaceAll(s, name, replacement)
	}
	s = strings.Replace(s, "// Code generated by gnark DO NOT EDIT", "// Derived from gnark v0.15.0 BLS12-381 PLONK Solidity template. DO NOT EDIT", 1)
	_, err := io.WriteString(w, s)
	return err
}
