// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.30;
import {EntryExitLedger} from "../src/EntryExitLedger.sol";
import {IZkVerifier} from "../src/IZkVerifier.sol";
import {Poseidon2BLS12381} from "../src/generated/Poseidon2BLS12381.sol";
import {ProcessPolicyVerifier} from "../src/ProcessPolicyVerifier.sol";
import {StorageProcessVerifier} from "../src/generated/storage-process/StorageProcessVerifier.sol";
interface VmM5{function readFile(string calldata)external view returns(string memory);function parseJsonBytes(string calldata,string calldata)external pure returns(bytes memory);function parseJsonUint(string calldata,string calldata)external pure returns(uint256);function parseJsonUintArray(string calldata,string calldata)external pure returns(uint256[] memory);function prank(address)external;function expectRevert(bytes4)external;}
contract AlwaysVerifier is IZkVerifier{function Verify(bytes calldata,uint256[] calldata)external pure returns(bool){return true;}}
contract ProcessPolicyTest{
 VmM5 constant vm=VmM5(address(uint160(uint256(keccak256("hevm cheat code")))));address constant ISSUER=address(0x1001);address constant AUTHORITY=address(0x2001);address constant RELAYER=address(0x3001);string fixture;string optimized;EntryExitLedger ledger;ProcessPolicyVerifier constantVerifier;StorageProcessVerifier storageVerifier;
 function setUp()public{fixture=vm.readFile("test/fixtures/m5-proofs.json");optimized=vm.readFile("../artifacts/development/m5/process-policy-3-2/optimized-vk.json");Poseidon2BLS12381 h=new Poseidon2BLS12381();AlwaysVerifier mock=new AlwaysVerifier();constantVerifier=new ProcessPolicyVerifier();storageVerifier=new StorageProcessVerifier();ledger=new EntryExitLedger(address(mock),address(mock),address(mock),address(mock),address(mock),address(mock),address(mock),address(h));ledger.setEntryIssuer(ISSUER,true);ledger.registerPolicyAuthority(AUTHORITY);}
 function testCanonicalPolicyProcessAndStorageVerifier()public{uint256 policyRef=_registerAndGrant();_entries();uint256[3] memory nf=_nf();uint256[2] memory out=_out();vm.prank(RELAYER);ledger.process(_proof(),policyRef,_u(".ScopeRef"),_u(".NoteRoot"),nf,out);require(ledger.noteLeafCount()==_u(".FinalCount"),"count");require(ledger.currentNoteRoot()==_u(".FinalRoot"),"root");for(uint256 i=0;i<3;i++)require(ledger.noteNullifiers(nf[i]),"nf");require(constantVerifier.Verify(_proof(),_publicInputs()),"constant");uint256[38] memory words=_words();bytes32 hash=sha256(abi.encode(words));storageVerifier.registerVK(policyRef,words,hash);require(storageVerifier.verifyForPolicy(policyRef,_proof(),_publicInputs()),"storage");require(storageVerifier.getVKHash(policyRef)==hash,"hash");}
 function testGrantDisableAndAuthorityRules()public{vm.prank(address(0x999));vm.expectRevert(EntryExitLedger.NotPolicyAuthority.selector);ledger.reservePolicy(6);vm.prank(AUTHORITY);uint256 p=ledger.reservePolicy(6);bytes32 h=bytes32(uint256(1));vm.prank(AUTHORITY);ledger.registerPolicy(p,3,2,h,address(constantVerifier));_entries();vm.expectRevert(EntryExitLedger.MissingPolicyGrant.selector);ledger.process(_proof(),p,_u(".ScopeRef"),_u(".NoteRoot"),_nf(),_out());vm.prank(AUTHORITY);ledger.setPolicyGrant(p,_u(".ScopeRef"),true);vm.prank(AUTHORITY);ledger.disablePolicy(p);vm.expectRevert(EntryExitLedger.DisabledPolicy.selector);ledger.process(_proof(),p,_u(".ScopeRef"),_u(".NoteRoot"),_nf(),_out());vm.prank(AUTHORITY);vm.expectRevert(EntryExitLedger.DisabledPolicy.selector);ledger.disablePolicy(p);}
 function _registerAndGrant()internal returns(uint256 p){vm.prank(AUTHORITY);p=ledger.reservePolicy(6);require(p==_u(".PolicyRef"),"policyRef");uint256[38] memory words=_words();bytes32 h=sha256(abi.encode(words));vm.prank(AUTHORITY);ledger.registerPolicy(p,3,2,h,address(constantVerifier));vm.prank(AUTHORITY);ledger.setPolicyGrant(p,_u(".ScopeRef"),true);}
 function _entries()internal{for(uint256 i=0;i<3;i++){vm.prank(ISSUER);ledger.entry(hex"01",_u(string.concat(".Entries[",_s(i),"].Commitment")));}}
 function _publicInputs()internal view returns(uint256[] memory p){p=new uint256[](8);p[0]=_u(".PolicyRef");p[1]=_u(".ScopeRef");p[2]=_u(".NoteRoot");for(uint256 i=0;i<3;i++)p[3+i]=_u(string.concat(".NF[",_s(i),"]"));p[6]=_u(".CMOut[0]");p[7]=_u(".CMOut[1]");}
 function _nf()internal view returns(uint256[3] memory v){for(uint256 i=0;i<3;i++)v[i]=_u(string.concat(".NF[",_s(i),"]"));}function _out()internal view returns(uint256[2] memory v){v[0]=_u(".CMOut[0]");v[1]=_u(".CMOut[1]");}
 function _words()internal view returns(uint256[38] memory v){uint256[] memory d=vm.parseJsonUintArray(optimized,".words");require(d.length==38,"words");for(uint256 i=0;i<38;i++)v[i]=d[i];}
 function _proof()internal view returns(bytes memory){return vm.parseJsonBytes(fixture,".proof");}function _u(string memory k)internal view returns(uint256){return vm.parseJsonUint(fixture,k);}function _s(uint256 v)internal pure returns(string memory){if(v==0)return"0";if(v==1)return"1";return"2";}
}
